import json
import xml.etree.ElementTree as ET
from typing import Any, Union

from bpmn_assistant.config import logger
from bpmn_assistant.core.schemas import model_type
from bpmn_assistant.services import BpmnProcessTransformer

BPMN_NS = "http://www.omg.org/spec/BPMN/20100524/MODEL"
BPMNDI_NS = "http://www.omg.org/spec/BPMN/20100524/DI"
DC_NS = "http://www.omg.org/spec/DD/20100524/DC"
DI_NS = "http://www.omg.org/spec/DD/20100524/DI"


class BpmnXmlGenerator:
    """
    Class to generate BPMN XML from the BPMN process data in JSON format.

    Accepts three top-level shapes (see core.schemas.model_type):
      - a bare process list (legacy single-pool orchestration)
      - a collaboration dict {participants, message_flows}
      - a choreography dict {participants, choreography}
    """

    def __init__(self):
        self.transformer = BpmnProcessTransformer()

    def create_bpmn_xml(self, model: Union[list[dict], dict]) -> str:
        """
        Create BPMN XML from the model data, dispatching on the model type.
        Args:
            model: BPMN process structure generated by the LLM. Either a process
                list (legacy) or a collaboration/choreography dict.
        Returns:
            The BPMN XML string.
        """
        kind = model_type(model)

        if kind == "collaboration":
            return self.create_collaboration_xml(model)
        if kind == "choreography":
            return self.create_choreography_xml(model)

        # Legacy single-process path (unchanged output: Process_1)
        process = model["process"] if isinstance(model, dict) else model
        root = self._create_root()
        transformed_process = self.transformer.transform(process)
        logger.debug(
            f"Transformed process:\n{json.dumps(transformed_process, indent=2)}"
        )
        self._append_process(root, "Process_1", transformed_process)
        return ET.tostring(root, encoding="unicode")

    def create_collaboration_xml(self, model: dict) -> str:
        """
        Create BPMN XML for a collaboration (pools + message flows).
        Emits a <collaboration> with one <participant> per pool and a sibling
        <process> per non-black-box participant.
        """
        participants = model["participants"]
        message_flows = model.get("message_flows", [])

        root = self._create_root()

        collaboration = ET.SubElement(root, "collaboration")
        collaboration.set("id", "Collaboration_1")

        # Pre-compute which participants have an inline process
        process_refs: dict[str, str] = {}
        for participant in participants:
            if participant.get("process"):
                process_refs[participant["id"]] = f"Process_{participant['id']}"

        # <participant> entries (with processRef only for non-black-box pools)
        for participant in participants:
            p_elem = ET.SubElement(collaboration, "participant")
            p_elem.set("id", participant["id"])
            p_elem.set("name", participant["name"])
            if participant["id"] in process_refs:
                p_elem.set("processRef", process_refs[participant["id"]])

        # <messageFlow> entries live inside <collaboration>
        for mf in message_flows:
            mf_elem = ET.SubElement(collaboration, "messageFlow")
            mf_elem.set("id", mf["id"])
            mf_elem.set("sourceRef", mf["sourceRef"])
            mf_elem.set("targetRef", mf["targetRef"])
            if mf.get("label"):
                mf_elem.set("name", mf["label"])

        # One <process> per non-black-box participant, reusing the transformer
        for participant in participants:
            if not participant.get("process"):
                continue
            transformed = self.transformer.transform(participant["process"])
            self._append_process(root, process_refs[participant["id"]], transformed)

        return ET.tostring(root, encoding="unicode")

    def create_choreography_xml(self, model: dict) -> str:
        """
        Create BPMN XML for a choreography. Choreography tasks connect via
        sequence flows just like tasks, so the existing flattening logic is
        reused (the transformer treats choreographyTask as a plain node).
        """
        participants = model["participants"]
        choreography = model["choreography"]

        # Build a lookup of choreography-task metadata before flattening, since
        # the transformer drops the participant/message fields.
        task_meta = {
            el["id"]: el
            for el in self._iter_all_elements(choreography)
            if el.get("type") == "choreographyTask"
        }

        root = self._create_root()

        # Collect <message> definitions referenced by choreography tasks
        message_defs: dict[str, str] = {}  # message_id -> name
        for tid, meta in task_meta.items():
            if meta.get("message"):
                message_defs[f"Message_{tid}"] = meta["message"]
            if meta.get("return_message"):
                message_defs[f"Message_{tid}_return"] = meta["return_message"]

        for msg_id, msg_name in message_defs.items():
            msg_elem = ET.SubElement(root, "message")
            msg_elem.set("id", msg_id)
            msg_elem.set("name", msg_name)

        choreography_elem = ET.SubElement(root, "choreography")
        choreography_elem.set("id", "Choreography_1")

        # Participant bands
        for participant in participants:
            p_elem = ET.SubElement(choreography_elem, "participant")
            p_elem.set("id", participant["id"])
            p_elem.set("name", participant["name"])

        # Message flows (one per task message). Declared here so the
        # <messageFlowRef> on each choreographyTask resolves. sourceRef/targetRef
        # are participant ids (the bands), not element ids.
        for tid, meta in task_meta.items():
            if meta.get("message"):
                self._append_message_flow(
                    choreography_elem,
                    f"MessageFlow_{tid}",
                    meta["initiator"],
                    meta["recipient"],
                    f"Message_{tid}",
                )
            if meta.get("return_message"):
                self._append_message_flow(
                    choreography_elem,
                    f"MessageFlow_{tid}_return",
                    meta["recipient"],
                    meta["initiator"],
                    f"Message_{tid}_return",
                )

        transformed = self.transformer.transform(choreography)
        logger.debug(
            f"Transformed choreography:\n{json.dumps(transformed, indent=2)}"
        )

        for element in transformed["elements"]:
            meta = task_meta.get(element["id"])
            if meta is not None:
                self._append_choreography_task(choreography_elem, element, meta)
            else:
                self._append_element(choreography_elem, element)

        self._append_flows(choreography_elem, transformed["flows"])

        return ET.tostring(root, encoding="unicode")

    # --- helpers ---

    def _create_root(self) -> ET.Element:
        root = ET.Element("definitions")
        root.set("xmlns", BPMN_NS)
        root.set("xmlns:bpmndi", BPMNDI_NS)
        root.set("xmlns:dc", DC_NS)
        root.set("xmlns:di", DI_NS)
        root.set("id", "definitions_1")
        return root

    def _append_process(
        self, root: ET.Element, process_id: str, transformed_process: dict
    ) -> ET.Element:
        """
        Append a <process> element (with its elements and sequence flows) to root.
        Factored out so single-pool and per-participant processes share one path.
        """
        process_element = ET.SubElement(root, "process")
        process_element.set("id", process_id)
        process_element.set("isExecutable", "false")

        for element in transformed_process["elements"]:
            self._append_element(process_element, element)

        self._append_flows(process_element, transformed_process["flows"])

        return process_element

    def _append_element(self, parent: ET.Element, element: dict) -> ET.Element:
        elem = ET.SubElement(parent, element["type"])
        elem.set("id", element["id"])

        if element.get("label"):
            elem.set("name", element["label"])

        if "default_flow" in element and element["default_flow"]:
            elem.set("default", element["default_flow"])

        for incoming in element["incoming"]:
            ET.SubElement(elem, "incoming").text = incoming
        for outgoing in element["outgoing"]:
            ET.SubElement(elem, "outgoing").text = outgoing

        if "eventDefinition" in element and element["eventDefinition"]:
            event_def_type = element["eventDefinition"]
            event_def_elem = ET.SubElement(elem, event_def_type)
            event_def_elem.set("id", f"{event_def_type}_{element['id']}")

        return elem

    def _append_choreography_task(
        self, parent: ET.Element, element: dict, meta: dict
    ) -> ET.Element:
        """Append a <choreographyTask> with participant bands and message refs."""
        elem = ET.SubElement(parent, "choreographyTask")
        elem.set("id", element["id"])
        if meta.get("name"):
            elem.set("name", meta["name"])
        elem.set("initiatingParticipantRef", meta["initiator"])

        for incoming in element["incoming"]:
            ET.SubElement(elem, "incoming").text = incoming
        for outgoing in element["outgoing"]:
            ET.SubElement(elem, "outgoing").text = outgoing

        # Two participant bands (initiator first, recipient second)
        ET.SubElement(elem, "participantRef").text = meta["initiator"]
        ET.SubElement(elem, "participantRef").text = meta["recipient"]

        if meta.get("message"):
            ET.SubElement(elem, "messageFlowRef").text = f"MessageFlow_{element['id']}"
        if meta.get("return_message"):
            ET.SubElement(
                elem, "messageFlowRef"
            ).text = f"MessageFlow_{element['id']}_return"

        return elem

    def _append_message_flow(
        self,
        parent: ET.Element,
        flow_id: str,
        source_ref: str,
        target_ref: str,
        message_ref: str,
    ) -> ET.Element:
        """Append a choreography-level <messageFlow> (participant -> participant)."""
        mf = ET.SubElement(parent, "messageFlow")
        mf.set("id", flow_id)
        mf.set("sourceRef", source_ref)
        mf.set("targetRef", target_ref)
        mf.set("messageRef", message_ref)
        return mf

    def _append_flows(self, parent: ET.Element, flows: list[dict]) -> None:
        for flow in flows:
            seq_flow = ET.SubElement(parent, "sequenceFlow")
            seq_flow.set("id", flow["id"])
            seq_flow.set("sourceRef", flow["sourceRef"])
            seq_flow.set("targetRef", flow["targetRef"])
            if flow["condition"]:
                seq_flow.set("name", flow["condition"])

    def _iter_all_elements(self, process: list[dict]) -> list[dict]:
        """Recursively yield every element in a (possibly branched) process list."""
        result: list[dict] = []
        for element in process:
            result.append(element)
            if "branches" in element:
                for branch in element["branches"]:
                    # Exclusive/inclusive branches are dicts with a 'path';
                    # parallel branches are bare lists.
                    path = branch.get("path", branch) if isinstance(branch, dict) else branch
                    result.extend(self._iter_all_elements(path))
        return result
